blank_issues_enabled: true
contact_links:
  - name: Open a discussion
    about: |
      Got a question about using rs-j? Need help troubleshooting? Feel free to open a discussion.
    url: https://github.com/madeja7396/rs-j/discussions/new
